feature: ETL DAG configuration from Universidad de Flores / Villa Maria
alkemyTech/OT214-Python pull request #12
Opened 2022-05-24 19:55 UTC by matiaspariente

Tarea: https://alkemy-labs.atlassian.net/browse/OT214-28

Resumen: Se configuro el Dag y se documentaron los operators que se deberían utilizar a futuro para hacer las consultas SQL de cada una de las universidades.

Aclaraciones: considerando que de las consultas SQL en las 2 universidades son distintas y que los datos que vienen tampoco son los mismos tome la decisión de separar por universidad tanto los operators para la consulta a la base de datos ( son distintas querys) como el procesamiento de los datos consultados ya que contienen distintos parámetros ( ejemplo código postal / localidad) , una vez procesados y normalizados los datos si utilizaría el mismo operator para subir los datos procesados a S3.  Si bien se podría hacer ambas universidades en el mismo operator con la lógica correspondiente, considero que quedaría mejor estructurado de esta manera.

2022-05-27 16:22 UTC, matiaspariente commented
Tarea: https://alkemy-labs.atlassian.net/browse/OT214-28

Resumen: Se configuro el Dag y se documentaron los operators que se deberían utilizar a futuro para hacer las consultas SQL de cada una de las universidades.

Aclaraciones:  A raiz del nuevo sprint y los requerimiento solicitados. Se modifico la estructura de los dags que se habia hecho inicialmente, se realizara la extracción SQL de ambas universidades desde la misma tarea , lo mismo para el procesamiento de los datos, en cambio se utilizaran tareas separadas para la carga de la información procesada a S3. Se definieron los operators como PythonOperators que son los que finalmente se utilizaran.

2022-05-31 03:54 UTC, julianpalmerio requested changes
El codigo esta muy bien, te marque un solo detalle para cambiar.

2022-05-31 03:54 UTC, julianpalmerio commented on universidades_a/dags/universidades_a.py
> +    start_date=datetime.now(),
No es una buena practica utilizar fechas dinamicas como inicio del dag, cambiala por una fecha estatica.

2022-05-31 13:35 UTC, matiaspariente commented
Tarea: https://alkemy-labs.atlassian.net/browse/OT214-28

change requested: se cambio el start_date a una fecha estática (fecha de hoy)

2022-05-31 21:14 UTC, merged